apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: seating
bases:
- ../../base

patchesJson6902:
- target:
    group: kafka.strimzi.io
    version: v1beta1
    kind: Kafka
    name: seating
  path: patch-replicas.yaml