apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: seating
  labels:
    app.kubernetes.io/managed-by: operator
spec:
  kafka:
    # version: 2.6.0
    template:
      statefulset:
        metadata:
          labels:
            app.kubernetes.io/part-of: kafka
            app.kubernetes.io/component: kafka
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.3'
    resources:
      limits:
        memory: 2Gi
      requests:
        memory: 2Gi
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    template:
      statefulset:
        metadata:
          labels:
            app.kubernetes.io/part-of: kafka
            app.kubernetes.io/component: zookeeper
    replicas: 3
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"