apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: registration

configMapGenerator:
- name: registerdb-init
  files:
    - configs/90-init-database.sh
    - configs/schema.sql

resources:
  - db-pvc.yaml
  - db-secret.yaml
  - db-service.yaml
  - db-deployment.yaml
  - registration-ui-is.yaml
  - registration-ui-bc.yaml
  - registration-ui-svc.yaml
  - registration-ui-route.yaml
  - registration-ui-deploy.yaml
  - registration-live-ui-is.yaml
  - registration-live-ui-bc.yaml
  - registration-live-ui-svc.yaml
  - registration-live-ui-route.yaml
  - registration-live-ui-deploy.yaml
  - registration-command-is.yaml
  - registration-command-bc.yaml
  - registration-command-svc.yaml
  - registration-command-route.yaml
  - registration-command-deploy.yaml
  - registration-simulator-is.yaml
  - registration-simulator-bc.yaml
  - registration-simulator-svc.yaml
  - registration-simulator-deploy.yaml
  - registration-loader-is.yaml
  - registration-loader-bc.yaml
  - registration-loader-svc.yaml
  - registration-loader-deploy.yaml