apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/gnunn1/seating
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-04-24T21:43:22Z"
  generation: 1
  labels:
    app: register
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: registration-ui
    app.kubernetes.io/name: registration-ui
    app.kubernetes.io/part-of: register
    app.openshift.io/runtime: camel
  name: registration-ui
spec:
  lookupPolicy:
    local: false