apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apicast-configuration-url-secret
spec:
  encryptedData:
    password: AgCmJLPVu8z2P39Y+Xsz/cVSadbrRyqDVsIdF/M4OAhWtWaqwyZGZljbgFlcsGS4TdF2KhPnXfJ04JYlu3OZ7lFw3BR76p+/47In6lEvTYA96PedSeA9F36x0sb5TvleQOlFYjzPCel/NgAuA2m/3dQJuExxA/SsuUYWvCCL/KN6psk5H6Thbx8XTTxIVjMiHVeJZMrdgXqONOEgx2zO1W175nvT1DxcC+o0US/vR+P6mG6MPAcUiAx54IPUhC5jcU2teRr3LnqNeCfqdr+Q7iolbpmFt6XCe1J8sqcUZ1ZjnlDyFIEXJnkLkya+Ra0Cbtw9W52X8QvCijPE3goOdNoyxd6sItZ1mm/OdI4covgYuAfAM5uj/1CQcq4SeSWHrDQioVIGXir6Zg2umSEXHSLJKK67ySXnV2NqWfg6zncHFffk0ObbI5kJBqtfgsn1RDfARxwOd2cTjCGVsuh8pmP/DNSdQeYRw8gXz/4f/xvWny5Dt3e00uks6Jxh9w7ALgJQxcpySzp5PzMCWcXTcqJy5IkJGrBZJh2B3060wsVGRNZlTq3zhI/BnWNeBVwmyn1/5Yr8s2v4WhTFDJjBeXxILrH1UgO5tc9awUUr5S3TBlI8c8JApEJQcbS6uWuc3uR16c9RdsJ/Hn8J5IiRUXRJhJsYHVZazaXQnXnMqaWbJ7RBXaWu/nHkKkBCkLDHjNUQDvMeSqdX/Msj8fHxWMHxhTUL2nAtjwdlIb6cnSH7bAnBeo+t8FtsF2DC9KVyMMN+22JWuqhBPSSpGbPjeIqJ+QxQ1ZuDM+eyV9bzBjCLxwx4+MG6JRQ8WmTVi5s2B2ON9w==
  template:
    metadata:
      name: apicast-configuration-url-secret
      namespace: seating
    type: kubernetes.io/basic-auth