apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: fuse76-console-tls-serving
  labels:
    app: fuse76-console
    component: fuse76-console
    group: console
    version: "1.6"
  name: fuse76-console
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: nginx
  selector:
    app: fuse76-console
    component: fuse76-console
    group: console
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
