apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/gnunn1/seating
  labels:
    app: analytics
    app.kubernetes.io/component: analytic-listener
    app.kubernetes.io/instance: analytic-listener
    app.kubernetes.io/name: analytic-listener
    app.kubernetes.io/part-of: analytics
    app.openshift.io/runtime: camel
  name: analytic-listener
spec:
  lookupPolicy:
    local: false