apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: analytics
    app.kubernetes.io/name: analytic
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: analytics
    app.kubernetes.io/instance: analyticdb
    app.openshift.io/runtime: mariadb
  name: analyticdb
stringData:
  database-name: analyticdb
  database-password: password
  database-root-password: password
  database-user: dbuser