apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: analytics

configMapGenerator:
- name: analyticdb-init
  files:
    - configs/90-init-database.sh
    - configs/schema.sql

resources:
- db-pvc.yaml
- db-secret.yaml
- db-service.yaml
- db-deployment.yaml
- analytic-ui-is.yaml
- analytic-ui-bc.yaml
- analytic-ui-deploy.yaml
- analytic-ui-svc.yaml
- analytic-ui-route.yaml
- analytic-listener-is.yaml
- analytic-listener-bc.yaml
- analytic-listener-deploy.yaml
- analytic-listener-svc.yaml
- analytic-listener-route.yaml