{
 "title": "Fuse Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "JVM Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_used{service!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "JVM GC Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_sum{service!=\"\"}[5m])) by (service)"
    }
   ]
  },
  {
   "title": "JVM GC Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_collection_seconds_count{service!=\"\"}[5m])) by (service)"
    }
   ]
  },
  { "title": "Fuse Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Route Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service)(rate(org_apache_camel_TotalProcessingTime{type=\"routes\"}[5m]))"
    }
   ]
  },
  {
   "title": "Last Processing Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_LastProcessingTime[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Exchanges Completed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_ExchangesCompleted{service!=\"\"}[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Exchanges in Flight",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_ExchangesInflight{service!=\"\"}[5m])) by (service)"
    }
   ]
  },
  {
   "title": "Exchanges Failed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(org_apache_camel_ExchangesFailed{service!=\"\"}[5m])) by (service)"
    }
   ]
  }
 ]
}