apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- grafana-kafka-dashboard.yaml
- grafana-kafka-exporter-dashboard.yaml
- grafana-zookeeper-dashboard.yaml
- grafana-fuse-dashboard.yaml