apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seating-monitoring

bases:
- ../../base

resources:
- namespace.yaml

patchesJson6902:
- target:
    group: operators.coreos.com
    version: v1
    kind: OperatorGroup
    name: monitoring
  path: namespace-patch.yaml