
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seat-ui
spec:
  template:
    spec:
      containers:
        - name: server
          env:
          - name: ROUTE_HOSTNAME
            value: http://seat-reader-seating.apps.cluster.ocplab.com