apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -prod

bases:
- ../../base

patchesJson6902:
- target:
    version: v1
    group: apps.openshift.io
    kind: DeploymentConfig
    name: apicast-prod
  path: patch-prod-dc.yaml