apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    app: server
    app.kubernetes.io/name: seatsdb
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: seatsdb
    app.kubernetes.io/part-of: seats
  name: seatsdb
stringData:
  database-name: seatsdb
  database-password: seats1234
  database-root-password: seats1234
  database-user: seats
