apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: seats

configMapGenerator:
- name: seatsdb-init
  files:
    - configs/90-init-database.sh
    - configs/schema.sql

resources:
  - db-pvc.yaml
  - db-secret.yaml
  - db-service.yaml
  - db-deployment.yaml
  - seat-reader-is.yaml
  - seat-reader-bc.yaml
  - seat-reader-svc.yaml
  - seat-reader-route.yaml
  - seat-reader-deploy.yaml
  - seat-listener-is.yaml
  - seat-listener-bc.yaml
  - seat-listener-svc.yaml
  - seat-listener-deploy.yaml
  - seat-ui-is.yaml
  - seat-ui-bc.yaml
  - seat-ui-svc.yaml
  - seat-ui-route.yaml
  - seat-ui-deploy.yaml
