apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/gnunn1/seating
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: "2020-04-25T16:44:16Z"
  labels:
    app: seats
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: seat-request
    app.kubernetes.io/name: seat-request
    app.kubernetes.io/part-of: seats
    app.openshift.io/runtime: camel
  name: seat-request
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: seat-request:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /seat-request
    git:
      ref: master
      uri: https://github.com/gnunn1/seating
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fuse7-java-openshift:1.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  # - generic:
  #     secretReference:
  #       name: seat-request-generic-webhook-secret
  #   type: Generic
  # - github:
  #     secretReference:
  #       name: seat-request-github-webhook-secret
  #   type: GitHub
  - imageChange:
    type: ImageChange
  - type: ConfigChange