apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/vcs-ref: master
    app.openshift.io/vcs-uri: https://github.com/gnunn1/seating
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"seat-reader:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"seat-reader\")].image"}]'
    app.openshift.io/connects-to: seatsdb
  labels:
    app: seats
    app.kubernetes.io/component: service
    app.kubernetes.io/instance: seat-reader
    app.kubernetes.io/name: seat-reader
    app.kubernetes.io/part-of: seats
    app.openshift.io/runtime: camel
    fuse-prometheus: "true"
  name: seat-reader
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: seat-reader
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: seat-reader
        deploymentconfig: seat-reader
        fuse-prometheus: "true"
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/seating/seat-reader
        imagePullPolicy: Always
        name: seat-reader
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: seatsdb
              key: database-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: seatsdb
              key: database-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: seatsdb
              key: database-name
        - name: MYSQL_SERVICE
          value: seatsdb
        - name: SPRING_APPLICATION_JSON
          value: '{"server":{"undertow":{"io-threads":1, "worker-threads":2 }}}'
        - name: JAEGER_SERVICE_NAME
          value: seat-reader
        - name: JAEGER_SAMPLER_TYPE
          value: const
        - name: JAEGER_SAMPLER_PARAM
          value: "1"
        - name: JAEGER_ENDPOINT
          value: http://jaeger-collector.seating-monitoring:14268/api/traces
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
          name: jolokia
        - containerPort: 8081
          protocol: TCP
        - containerPort: 9779
          protocol: TCP
          name: prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30